"""ATT&CK Navigator layer export."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.threat_intel.attack_mapping import AttackMapping

logger = logging.getLogger(__name__)

# Default version strings (update when Navigator releases new versions)
# Check https://github.com/mitre-attack/attack-navigator for latest versions
DEFAULT_ATTACK_VERSION = "14"
DEFAULT_NAVIGATOR_VERSION = "4.9.1"
DEFAULT_LAYER_VERSION = "4.5"

# Color gradient for confidence levels
CONFIDENCE_COLORS = {
    "critical": "#ff0000",  # Red
    "high": "#ff6600",  # Orange
    "medium": "#ffcc00",  # Yellow
    "low": "#99cc00",  # Light green
}


def export_navigator_layer(
    mapping: "AttackMapping",
    name: str = "PCAP Analysis",
    description: str | None = None,
    attack_version: str | None = None,
    navigator_version: str | None = None,
    layer_version: str | None = None,
) -> dict:
    """
    Generate ATT&CK Navigator layer JSON.

    Can be imported directly into https://mitre-attack.github.io/attack-navigator/

    Args:
        mapping: AttackMapping from analysis
        name: Layer name
        description: Optional description
        attack_version: ATT&CK version (default: DEFAULT_ATTACK_VERSION)
        navigator_version: Navigator version (default: DEFAULT_NAVIGATOR_VERSION)
        layer_version: Layer schema version (default: DEFAULT_LAYER_VERSION)

    Returns:
        Navigator layer as dict (can be serialized to JSON)
    """
    techniques = []

    for tech in mapping.techniques:
        # Calculate score (0-100)
        score = int(tech.confidence * 100)

        # Determine color based on confidence
        color = _confidence_to_color(tech.confidence)

        # Build comment from evidence
        comment = "; ".join(tech.evidence) if tech.evidence else ""

        techniques.append(
            {
                "techniqueID": tech.technique_id,
                "tactic": tech.tactic,
                "score": score,
                "color": color,
                "comment": comment,
                "enabled": True,
                "showSubtechniques": False,
            }
        )

    # Build layer structure
    layer = {
        "name": name,
        "versions": {
            "attack": attack_version or DEFAULT_ATTACK_VERSION,
            "navigator": navigator_version or DEFAULT_NAVIGATOR_VERSION,
            "layer": layer_version or DEFAULT_LAYER_VERSION,
        },
        "domain": "enterprise-attack",
        "description": description or f"Generated by PCAP Hunter on {datetime.now(tz=timezone.utc).isoformat()}",
        "filters": {
            "platforms": [
                "Linux",
                "macOS",
                "Windows",
                "Network",
                "PRE",
                "Containers",
                "Office 365",
                "SaaS",
                "Google Workspace",
                "IaaS",
                "Azure AD",
            ]
        },
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": True,
            "showName": True,
            "showAggregateScores": False,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#ffeb3b", "#ff9800", "#f44336"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Low Confidence (< 40%)", "color": "#99cc00"},
            {"label": "Medium Confidence (40-60%)", "color": "#ffcc00"},
            {"label": "High Confidence (60-80%)", "color": "#ff6600"},
            {"label": "Critical Confidence (> 80%)", "color": "#ff0000"},
        ],
        "metadata": [
            {"name": "generated_by", "value": "PCAP Hunter"},
            {"name": "generated_at", "value": datetime.now(tz=timezone.utc).isoformat()},
            {"name": "technique_count", "value": str(len(techniques))},
            {"name": "overall_severity", "value": mapping.overall_severity},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }

    return layer


def _confidence_to_color(confidence: float) -> str:
    """Convert confidence score to color."""
    if confidence >= 0.8:
        return CONFIDENCE_COLORS["critical"]
    elif confidence >= 0.6:
        return CONFIDENCE_COLORS["high"]
    elif confidence >= 0.4:
        return CONFIDENCE_COLORS["medium"]
    else:
        return CONFIDENCE_COLORS["low"]


def export_navigator_json(
    mapping: "AttackMapping",
    name: str = "PCAP Analysis",
    description: str | None = None,
    indent: int = 2,
) -> bytes:
    """
    Export Navigator layer as JSON bytes.

    Args:
        mapping: AttackMapping from analysis
        name: Layer name
        description: Optional description
        indent: JSON indentation

    Returns:
        UTF-8 encoded JSON bytes
    """
    layer = export_navigator_layer(mapping, name, description)
    return json.dumps(layer, indent=indent, ensure_ascii=False).encode("utf-8")


def generate_navigator_filename(name: str = "attack_layer") -> str:
    """Generate timestamped filename for Navigator export."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    # Sanitize name
    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
    return f"{safe_name}_{timestamp}.json"


def create_comparison_layer(
    mappings: list[tuple[str, "AttackMapping"]],
    name: str = "Comparison",
) -> dict:
    """
    Create a comparison layer from multiple mappings.

    Args:
        mappings: List of (name, AttackMapping) tuples
        name: Overall layer name

    Returns:
        Navigator layer with combined techniques
    """
    # Combine techniques from all mappings
    combined_techniques: dict[str, dict] = {}

    for mapping_name, mapping in mappings:
        for tech in mapping.techniques:
            key = f"{tech.technique_id}:{tech.tactic}"

            if key not in combined_techniques:
                combined_techniques[key] = {
                    "techniqueID": tech.technique_id,
                    "tactic": tech.tactic,
                    "score": 0,
                    "color": "",
                    "comment": "",
                    "enabled": True,
                    "metadata": [],
                }

            # Update with highest confidence
            current_score = combined_techniques[key]["score"]
            new_score = int(tech.confidence * 100)
            if new_score > current_score:
                combined_techniques[key]["score"] = new_score
                combined_techniques[key]["color"] = _confidence_to_color(tech.confidence)

            # Add source to comment
            evidence = f"[{mapping_name}] {'; '.join(tech.evidence)}"
            if combined_techniques[key]["comment"]:
                combined_techniques[key]["comment"] += f"\n{evidence}"
            else:
                combined_techniques[key]["comment"] = evidence

    # Build layer
    layer = {
        "name": name,
        "versions": {
            "attack": DEFAULT_ATTACK_VERSION,
            "navigator": DEFAULT_NAVIGATOR_VERSION,
            "layer": DEFAULT_LAYER_VERSION,
        },
        "domain": "enterprise-attack",
        "description": f"Comparison of {len(mappings)} analyses",
        "techniques": list(combined_techniques.values()),
        "gradient": {
            "colors": ["#ffffff", "#ffeb3b", "#ff9800", "#f44336"],
            "minValue": 0,
            "maxValue": 100,
        },
    }

    return layer
